/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVerifikasiRouteImport } from './routes/app.verifikasi'
import { Route as AppTugasRouteImport } from './routes/app.tugas'
import { Route as AppProfilRouteImport } from './routes/app.profil'
import { Route as AppMonitoringTugasRouteImport } from './routes/app.monitoring-tugas'
import { Route as AppKpiRouteImport } from './routes/app.kpi'
import { Route as AppAbsensiRouteImport } from './routes/app.absensi'
import { Route as AppMasterSopRouteImport } from './routes/app.master.sop'
import { Route as AppMasterKaryawanRouteImport } from './routes/app.master.karyawan'
import { Route as AppMasterJadwalRouteImport } from './routes/app.master.jadwal'
import { Route as AppMasterCabangRouteImport } from './routes/app.master.cabang'

const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifikasiRoute = AppVerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => AppRoute,
} as any)
const AppTugasRoute = AppTugasRouteImport.update({
  id: '/tugas',
  path: '/tugas',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringTugasRoute = AppMonitoringTugasRouteImport.update({
  id: '/monitoring-tugas',
  path: '/monitoring-tugas',
  getParentRoute: () => AppRoute,
} as any)
const AppKpiRoute = AppKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AppRoute,
} as any)
const AppAbsensiRoute = AppAbsensiRouteImport.update({
  id: '/absensi',
  path: '/absensi',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterSopRoute = AppMasterSopRouteImport.update({
  id: '/master/sop',
  path: '/master/sop',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterKaryawanRoute = AppMasterKaryawanRouteImport.update({
  id: '/master/karyawan',
  path: '/master/karyawan',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterJadwalRoute = AppMasterJadwalRouteImport.update({
  id: '/master/jadwal',
  path: '/master/jadwal',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterCabangRoute = AppMasterCabangRouteImport.update({
  id: '/master/cabang',
  path: '/master/cabang',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/app/absensi': typeof AppAbsensiRoute
  '/app/kpi': typeof AppKpiRoute
  '/app/monitoring-tugas': typeof AppMonitoringTugasRoute
  '/app/profil': typeof AppProfilRoute
  '/app/tugas': typeof AppTugasRoute
  '/app/verifikasi': typeof AppVerifikasiRoute
  '/app/': typeof AppIndexRoute
  '/app/master/cabang': typeof AppMasterCabangRoute
  '/app/master/jadwal': typeof AppMasterJadwalRoute
  '/app/master/karyawan': typeof AppMasterKaryawanRoute
  '/app/master/sop': typeof AppMasterSopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/app/absensi': typeof AppAbsensiRoute
  '/app/kpi': typeof AppKpiRoute
  '/app/monitoring-tugas': typeof AppMonitoringTugasRoute
  '/app/profil': typeof AppProfilRoute
  '/app/tugas': typeof AppTugasRoute
  '/app/verifikasi': typeof AppVerifikasiRoute
  '/app': typeof AppIndexRoute
  '/app/master/cabang': typeof AppMasterCabangRoute
  '/app/master/jadwal': typeof AppMasterJadwalRoute
  '/app/master/karyawan': typeof AppMasterKaryawanRoute
  '/app/master/sop': typeof AppMasterSopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/app/absensi': typeof AppAbsensiRoute
  '/app/kpi': typeof AppKpiRoute
  '/app/monitoring-tugas': typeof AppMonitoringTugasRoute
  '/app/profil': typeof AppProfilRoute
  '/app/tugas': typeof AppTugasRoute
  '/app/verifikasi': typeof AppVerifikasiRoute
  '/app/': typeof AppIndexRoute
  '/app/master/cabang': typeof AppMasterCabangRoute
  '/app/master/jadwal': typeof AppMasterJadwalRoute
  '/app/master/karyawan': typeof AppMasterKaryawanRoute
  '/app/master/sop': typeof AppMasterSopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/bootstrap'
    | '/app/absensi'
    | '/app/kpi'
    | '/app/monitoring-tugas'
    | '/app/profil'
    | '/app/tugas'
    | '/app/verifikasi'
    | '/app/'
    | '/app/master/cabang'
    | '/app/master/jadwal'
    | '/app/master/karyawan'
    | '/app/master/sop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bootstrap'
    | '/app/absensi'
    | '/app/kpi'
    | '/app/monitoring-tugas'
    | '/app/profil'
    | '/app/tugas'
    | '/app/verifikasi'
    | '/app'
    | '/app/master/cabang'
    | '/app/master/jadwal'
    | '/app/master/karyawan'
    | '/app/master/sop'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/bootstrap'
    | '/app/absensi'
    | '/app/kpi'
    | '/app/monitoring-tugas'
    | '/app/profil'
    | '/app/tugas'
    | '/app/verifikasi'
    | '/app/'
    | '/app/master/cabang'
    | '/app/master/jadwal'
    | '/app/master/karyawan'
    | '/app/master/sop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BootstrapRoute: typeof BootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verifikasi': {
      id: '/app/verifikasi'
      path: '/verifikasi'
      fullPath: '/app/verifikasi'
      preLoaderRoute: typeof AppVerifikasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tugas': {
      id: '/app/tugas'
      path: '/tugas'
      fullPath: '/app/tugas'
      preLoaderRoute: typeof AppTugasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring-tugas': {
      id: '/app/monitoring-tugas'
      path: '/monitoring-tugas'
      fullPath: '/app/monitoring-tugas'
      preLoaderRoute: typeof AppMonitoringTugasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kpi': {
      id: '/app/kpi'
      path: '/kpi'
      fullPath: '/app/kpi'
      preLoaderRoute: typeof AppKpiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/absensi': {
      id: '/app/absensi'
      path: '/absensi'
      fullPath: '/app/absensi'
      preLoaderRoute: typeof AppAbsensiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/master/sop': {
      id: '/app/master/sop'
      path: '/master/sop'
      fullPath: '/app/master/sop'
      preLoaderRoute: typeof AppMasterSopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/master/karyawan': {
      id: '/app/master/karyawan'
      path: '/master/karyawan'
      fullPath: '/app/master/karyawan'
      preLoaderRoute: typeof AppMasterKaryawanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/master/jadwal': {
      id: '/app/master/jadwal'
      path: '/master/jadwal'
      fullPath: '/app/master/jadwal'
      preLoaderRoute: typeof AppMasterJadwalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/master/cabang': {
      id: '/app/master/cabang'
      path: '/master/cabang'
      fullPath: '/app/master/cabang'
      preLoaderRoute: typeof AppMasterCabangRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAbsensiRoute: typeof AppAbsensiRoute
  AppKpiRoute: typeof AppKpiRoute
  AppMonitoringTugasRoute: typeof AppMonitoringTugasRoute
  AppProfilRoute: typeof AppProfilRoute
  AppTugasRoute: typeof AppTugasRoute
  AppVerifikasiRoute: typeof AppVerifikasiRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMasterCabangRoute: typeof AppMasterCabangRoute
  AppMasterJadwalRoute: typeof AppMasterJadwalRoute
  AppMasterKaryawanRoute: typeof AppMasterKaryawanRoute
  AppMasterSopRoute: typeof AppMasterSopRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAbsensiRoute: AppAbsensiRoute,
  AppKpiRoute: AppKpiRoute,
  AppMonitoringTugasRoute: AppMonitoringTugasRoute,
  AppProfilRoute: AppProfilRoute,
  AppTugasRoute: AppTugasRoute,
  AppVerifikasiRoute: AppVerifikasiRoute,
  AppIndexRoute: AppIndexRoute,
  AppMasterCabangRoute: AppMasterCabangRoute,
  AppMasterJadwalRoute: AppMasterJadwalRoute,
  AppMasterKaryawanRoute: AppMasterKaryawanRoute,
  AppMasterSopRoute: AppMasterSopRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BootstrapRoute: BootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
